// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetChartrepoRepoChartsNameVersionReader is a Reader for the GetChartrepoRepoChartsNameVersion structure.
type GetChartrepoRepoChartsNameVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChartrepoRepoChartsNameVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetChartrepoRepoChartsNameVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetChartrepoRepoChartsNameVersionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetChartrepoRepoChartsNameVersionForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetChartrepoRepoChartsNameVersionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetChartrepoRepoChartsNameVersionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetChartrepoRepoChartsNameVersionOK creates a GetChartrepoRepoChartsNameVersionOK with default headers values
func NewGetChartrepoRepoChartsNameVersionOK() *GetChartrepoRepoChartsNameVersionOK {
	return &GetChartrepoRepoChartsNameVersionOK{}
}

/*GetChartrepoRepoChartsNameVersionOK handles this case with default header values.

The detailed information of the chart entry
*/
type GetChartrepoRepoChartsNameVersionOK struct {
}

func (o *GetChartrepoRepoChartsNameVersionOK) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}/{version}][%d] getChartrepoRepoChartsNameVersionOK ", 200)
}

func (o *GetChartrepoRepoChartsNameVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameVersionUnauthorized creates a GetChartrepoRepoChartsNameVersionUnauthorized with default headers values
func NewGetChartrepoRepoChartsNameVersionUnauthorized() *GetChartrepoRepoChartsNameVersionUnauthorized {
	return &GetChartrepoRepoChartsNameVersionUnauthorized{}
}

/*GetChartrepoRepoChartsNameVersionUnauthorized handles this case with default header values.

Unauthorized
*/
type GetChartrepoRepoChartsNameVersionUnauthorized struct {
}

func (o *GetChartrepoRepoChartsNameVersionUnauthorized) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}/{version}][%d] getChartrepoRepoChartsNameVersionUnauthorized ", 401)
}

func (o *GetChartrepoRepoChartsNameVersionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameVersionForbidden creates a GetChartrepoRepoChartsNameVersionForbidden with default headers values
func NewGetChartrepoRepoChartsNameVersionForbidden() *GetChartrepoRepoChartsNameVersionForbidden {
	return &GetChartrepoRepoChartsNameVersionForbidden{}
}

/*GetChartrepoRepoChartsNameVersionForbidden handles this case with default header values.

Operation is forbidden
*/
type GetChartrepoRepoChartsNameVersionForbidden struct {
}

func (o *GetChartrepoRepoChartsNameVersionForbidden) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}/{version}][%d] getChartrepoRepoChartsNameVersionForbidden ", 403)
}

func (o *GetChartrepoRepoChartsNameVersionForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameVersionNotFound creates a GetChartrepoRepoChartsNameVersionNotFound with default headers values
func NewGetChartrepoRepoChartsNameVersionNotFound() *GetChartrepoRepoChartsNameVersionNotFound {
	return &GetChartrepoRepoChartsNameVersionNotFound{}
}

/*GetChartrepoRepoChartsNameVersionNotFound handles this case with default header values.

Not found
*/
type GetChartrepoRepoChartsNameVersionNotFound struct {
}

func (o *GetChartrepoRepoChartsNameVersionNotFound) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}/{version}][%d] getChartrepoRepoChartsNameVersionNotFound ", 404)
}

func (o *GetChartrepoRepoChartsNameVersionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameVersionInternalServerError creates a GetChartrepoRepoChartsNameVersionInternalServerError with default headers values
func NewGetChartrepoRepoChartsNameVersionInternalServerError() *GetChartrepoRepoChartsNameVersionInternalServerError {
	return &GetChartrepoRepoChartsNameVersionInternalServerError{}
}

/*GetChartrepoRepoChartsNameVersionInternalServerError handles this case with default header values.

Internal server error occurred
*/
type GetChartrepoRepoChartsNameVersionInternalServerError struct {
}

func (o *GetChartrepoRepoChartsNameVersionInternalServerError) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}/{version}][%d] getChartrepoRepoChartsNameVersionInternalServerError ", 500)
}

func (o *GetChartrepoRepoChartsNameVersionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
