// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetChartrepoRepoChartsNameReader is a Reader for the GetChartrepoRepoChartsName structure.
type GetChartrepoRepoChartsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChartrepoRepoChartsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetChartrepoRepoChartsNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetChartrepoRepoChartsNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetChartrepoRepoChartsNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetChartrepoRepoChartsNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetChartrepoRepoChartsNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetChartrepoRepoChartsNameOK creates a GetChartrepoRepoChartsNameOK with default headers values
func NewGetChartrepoRepoChartsNameOK() *GetChartrepoRepoChartsNameOK {
	return &GetChartrepoRepoChartsNameOK{}
}

/*GetChartrepoRepoChartsNameOK handles this case with default header values.

A list of chart entry
*/
type GetChartrepoRepoChartsNameOK struct {
}

func (o *GetChartrepoRepoChartsNameOK) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameOK ", 200)
}

func (o *GetChartrepoRepoChartsNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameUnauthorized creates a GetChartrepoRepoChartsNameUnauthorized with default headers values
func NewGetChartrepoRepoChartsNameUnauthorized() *GetChartrepoRepoChartsNameUnauthorized {
	return &GetChartrepoRepoChartsNameUnauthorized{}
}

/*GetChartrepoRepoChartsNameUnauthorized handles this case with default header values.

Unauthorized
*/
type GetChartrepoRepoChartsNameUnauthorized struct {
}

func (o *GetChartrepoRepoChartsNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameUnauthorized ", 401)
}

func (o *GetChartrepoRepoChartsNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameForbidden creates a GetChartrepoRepoChartsNameForbidden with default headers values
func NewGetChartrepoRepoChartsNameForbidden() *GetChartrepoRepoChartsNameForbidden {
	return &GetChartrepoRepoChartsNameForbidden{}
}

/*GetChartrepoRepoChartsNameForbidden handles this case with default header values.

Operation is forbidden
*/
type GetChartrepoRepoChartsNameForbidden struct {
}

func (o *GetChartrepoRepoChartsNameForbidden) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameForbidden ", 403)
}

func (o *GetChartrepoRepoChartsNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameNotFound creates a GetChartrepoRepoChartsNameNotFound with default headers values
func NewGetChartrepoRepoChartsNameNotFound() *GetChartrepoRepoChartsNameNotFound {
	return &GetChartrepoRepoChartsNameNotFound{}
}

/*GetChartrepoRepoChartsNameNotFound handles this case with default header values.

Not found
*/
type GetChartrepoRepoChartsNameNotFound struct {
}

func (o *GetChartrepoRepoChartsNameNotFound) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameNotFound ", 404)
}

func (o *GetChartrepoRepoChartsNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetChartrepoRepoChartsNameInternalServerError creates a GetChartrepoRepoChartsNameInternalServerError with default headers values
func NewGetChartrepoRepoChartsNameInternalServerError() *GetChartrepoRepoChartsNameInternalServerError {
	return &GetChartrepoRepoChartsNameInternalServerError{}
}

/*GetChartrepoRepoChartsNameInternalServerError handles this case with default header values.

Internal server error occurred
*/
type GetChartrepoRepoChartsNameInternalServerError struct {
}

func (o *GetChartrepoRepoChartsNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /chartrepo/{repo}/charts/{name}][%d] getChartrepoRepoChartsNameInternalServerError ", 500)
}

func (o *GetChartrepoRepoChartsNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
